name: Build & Publish Docker Image
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      IMG_NAME: ${{ github.event.repository.name }}
      IMG_VERSION: ${{ github.ref_name }}

    steps:
      - # Checkout the repo
        name: Checkout
        uses: actions/checkout@v3
      - # Log in to Docker registry
        name: Login to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - # Overwrite Version File
        name: Overwrite Compiled Version
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ./src/config/version.json
          write-mode: overwrite
          contents: |
            "${{env.IMG_VERSION}}"
      - # Set up QEMU
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - # Set up Docker Buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - # Build and tag Docker image
        name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ github.repository_owner }}/${{env.IMG_NAME}}:latest .
          docker tag ${{ secrets.REGISTRY_URL }}/${{ github.repository_owner }}/${{env.IMG_NAME}}:latest ${{ secrets.REGISTRY_URL }}/${{ github.repository_owner }}/${{env.IMG_NAME}}:${{ env.IMG_VERSION }}
      - # Push Docker image to Registry
        name: Push Docker image to Registry
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository_owner }}/${{env.IMG_NAME}}:latest
          docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository_owner }}/${{env.IMG_NAME}}:${{ env.IMG_VERSION }}
