name: Build and Push

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set-env
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME#*/}"
          if [[ "$REPO_NAME" == *--* ]]; then
            PART1="${REPO_NAME%%--*}"
            PART2="${REPO_NAME##*--}"
            echo "REPO_OWNER=$PART1" >> $GITHUB_ENV
            echo "IMG_NAME=$PART2" >> $GITHUB_ENV
          else
            echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
            echo "IMG_NAME=$REPO_NAME" >> $GITHUB_ENV
          fi

      - name: Determine version (MAJOR, MINOR, PATCH)
        id: determine-latest
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"

      - name: Print environment variables
        run: |
          echo "Repository: ${REPO_OWNER}/${IMG_NAME}:${{github.ref_name}} ${{secrets.REGISTRY_USERNAME}}"

      - # Log in to Docker registry
        name: Login to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=${{github.ref_name}} -t ${{ secrets.REGISTRY_URL }}/${REPO_OWNER}/${IMG_NAME}:${{github.ref_name}} .

      - name: Tag Docker image as latest if applicable
        run: |
          docker tag ${{ secrets.REGISTRY_URL }}/${REPO_OWNER}/${IMG_NAME}:${{github.ref_name}} ${{ secrets.REGISTRY_URL }}/${REPO_OWNER}/${IMG_NAME}:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/${REPO_OWNER}/${IMG_NAME}:${{github.ref_name}}
          docker push ${{ secrets.REGISTRY_URL }}/${REPO_OWNER}/${IMG_NAME}:latest
